# CC1=strace -e trace=file /usr/lib64/gcc/x86_64-suse-linux/7/cc1
# CC1=/usr/lib64/gcc/x86_64-suse-linux/7/cc1
# CC1=strace -e trace=file ./cc1

test: lfs.c lfs_error.c bitmap.c inode.c sync.c file.c test.c
	./runcc.sh
